### ISSUE TITLE
Document design principles 

### ISSUE THREAD

**Issue by mellertd** [TheJacksonLaboratory/ezomero#11]
We should probably settle on some design principles for this, and document for the benefit of potential contributors. We can use this issue as a discussion thread.

For example, we are currently avoiding returning or taking as parameters any omero or blitzgateway objects (other than the connection obj itself), to keep things more accessible for novice users. Instead, we are doing things like taking and returning OMERO IDs.

Other issues to consider:
  * How do we decide if/when to add dependencies
  * How do we go about deprecating/replacing functions
  * How do we make API decisions in general

**Comment by juliomateoslangerak** [comment]
I agree on the idea of using ids as a reference to omero objects and leave the omero wrappers aside. The only concern I would have is performance. How expensive is to request every time those objects?
Also, using plain ints as ids might not be a good idea in the sense that you not sum them.
I would consider creating a single class representing all of OMERO objects and exposing very basic attributes like id, name, description.

**Comment by mellertd** [comment]
Regarding performance, we've found that using the query service to return lists of image ids is much faster than returning the image objects and iterating over them to get the ids.

Can you expand on your second point about returning plain ints? We haven't seen any problems with this, but I am interested in what you think. I am very hesitant to create new classes -- I would say if someone wants the details of an image and are going to use an object to do it, might as well just grab the OMERO Image object, which gives you access to id, name, description and everything else too.

**Comment by juliomateoslangerak** [comment]
I understand that the query service would indeed be very quick to get the image ids. But you are rarely going to just get the id's. You will probably have to iterate over those ids later to get the image wrappers anyway. 

In a very simple case where you want to get the images in a dataset to do some calculation on some rois and you need the pixel size. working with image ids alone, you would have to call omero.getObject once to get the ROI, and a second time get the pixel size.

My point about using plain ints is that, ints implement a good number of functionality that is not meant for ids, like multiplication, summing, etc. Also, if you are meant to work with different databases, you may hold the same id and object for different data. Would it make sense to subclass Python's int and hide the wrapper as a 'hidden' _omero_object_wrapper attribute and that ezomero functions check if that wrapper is there or otherwise get it?

**Comment by mellertd** [comment]
We actually have many use cases where we are just working with ids. This in fact is what kicked off the library in the first place! And anyway, I think for people very concerned with performance that need to load every object, BlitzGateway and the Python bindings for the core API work quite well.

You'll notice the code now is not using the query service for everything. We certainly want to move that direction for GETs. Then for complex queries, I am thinking we can intersect sets of ids rather than try to convert Python arguments to HQL programmatically (which is beyond my brain's abilities, anyway).

Regarding the type of ids, I understand the concern, but our intention for this library is for use in an interactive shell or scripting context, and I just don't see many people running into the issues you are describing. For more "serious" usage, like writing a plugin or some client application, I think folks should be using the Python bindings or BlitzGateway API anyway (as above). This is a good note for the putative design principles doc, actually. As we mentioned in the introductory image.sc post, we are not aiming to replace BlitzGateway, but to complement it.

I think if we get a lot of feedback that plain `int`s are a problem, we can subclass Python's `int` as you describe. But in the spirit of keeping things as simple as possible until there is a clear need, we'll keep them plain `int` for now.

**Comment by mellertd** [comment]
I think this is more or less covered in #28
