### ISSUE TITLE
Extend all relevant functions to do cross-group queries

### ISSUE THREAD

**Issue by erickmartins** [TheJacksonLaboratory/ezomero#5]
Following PR #1 we should probably replicate that functionality to all functions where that is relevant - instead of only querying for objects in the user's default group, we should do cross-group queries (using `conn.SERVICE_OPTS.setOmeroGroup('-1')` before a query) and then safely switching group (using `set_group`, for example) when relevant, and finally switching back to the user's default group before returning.

**Comment by juliomateoslangerak** [comment]
That looks like something to implement using decorators

**Comment by will-moore** [comment]
For `omero-web` we use the `@login_required()` to `setOmeroGroup()` to `-1` by default. https://github.com/ome/omero-web/blob/c7eb75fd6b65edd2ffa3556bf8ba178c348e04d0/omeroweb/decorators.py#L229
This means that you don't have to worry about group context when *querying* for data.
You always need to set group when *saving* (if the function does that), but this is also true if your default state is to switch the user to their default group. So, you might consider a simple decorator that just sets the current group to `-1`?
But I think it could be tricky to come up with a decorator that sets the group context based on an object specified in the functions arguments, because the various functions have quite different arguments.

**Comment by juliomateoslangerak** [comment]
Would it make sense to use a decorator for the query functions getting one of the function arguments being 'across_groups=False' and, if True, temporary change the group to -1.

Something like:
``` python
def do_across_groups(f):
    def wrapper(*args, **kwargs):
        if kwargs['across_groups']:
            current_group_id = args[0].get_group_id()
            args[0].set_group_id(-1)
            f(*args, **kwargs)
            args[0].set_group_id(current_group_id)
        else:
            f(*args, **kwargs)
    return wrapper

@do_across_groups
def my_query_function(conn, arg1, arg2, kwarg1='X', kwarg2='Y', across_groups=False):  # across_groups eventually defaulting to True if it makes sense
    pass
```
This would require though that all functions using the decorator have connection as the first argument and a kwarg called across_groups

**Comment by will-moore** [comment]
That's pretty much what I was thinking.
You could check for `conn = kwargs.get("conn")` so that it doesn't have to be first argument.
Although it's a good convention anyway to have `conn` as first argument.

You might find that any function that does saving needs to set group explicitly. And all other functions can be 'across_groups`. So you may be able to use `cross_group=True` by default, and not need to add this argument to most functions?

**Comment by erickmartins** [comment]
Yeah, I think in general terms we want to keep usage as simple as possible - if someone says "I want to link this image to dataset 362" this should "just work" if the user has write access to that dataset, no matter whether that is on their default group or not, and should fail with a permissions warning if not. I think having a `cross_group=True` parameter by default works for that.

**Comment by mellertd** [comment]
This (should be) covered in #17 . Thanks everyone!
