### ISSUE TITLE
[FEATURE] Add description to ezimport

### ISSUE THREAD

**Issue by abhamacher** [TheJacksonLaboratory/ezomero#74]
Hello everyone,

I realized that with ezomero.post_image it's possible to add a "description" to the new image but with ezomero.ezimport it's not. Would it be possible to add this parameter to ezimport as well? Or is there another way I could add/ modify the image description with ezomero?

Thanks in advance
Anna

**Comment by erickmartins** [comment]
Hi Anna,

I think putting that into `ezimport` might be complicated - especially in cases where a single import can generate multiple images in OMERO. `post_image` gets away with it because we know it will generate a single image. Having a `put_image_description` function sounds feasible to me - I'll leave the issue open for that.

**Comment by mellertd** [comment]
merged, but we still need to build docs

**Comment by erickmartins** [comment]
Included in release 2.1.0.
